# Generated by Django 2.0.6 on 2018-06-13 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('waitlist', 'waitlist')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('name', models.TextField()),
                ('bio', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('name', models.TextField(null=True)),
                ('time', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('cancelled', 'cancelled'), ('draft', 'draft'), ('past', 'past'), ('proposed', 'proposed'), ('suggested', 'suggested'), ('upcoming', 'upcoming')], max_length=10)),
                ('local_date', models.DateField(null=True)),
                ('local_time', models.TimeField(null=True)),
                ('yes_rsvp_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='meetup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.Meetup'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.Attendee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.Event'),
        ),
    ]
