# Generated by Django 2.0.6 on 2018-06-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_auto_20180613_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='rsvp',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('waitlist', 'waitlist')], max_length=3, null=True),
        ),
    ]
