# Generated by Django 2.0.6 on 2018-06-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0003_auto_20180613_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='syncing',
            field=models.BooleanField(default=False),
        ),
    ]
